"""Initial migration after reset

Revision ID: e19f61da2d48
Revises: 
Create Date: 2025-07-04 14:31:17.272290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e19f61da2d48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pantry_id', sa.Integer(), nullable=False))
        batch_op.drop_column('pantry_level')

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('marketplace_item', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marketplace_item', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pantry_level', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('pantry_id')

    # ### end Alembic commands ###
