"""Change pantry_id to String

Revision ID: 2e833718e62c
Revises: 
Create Date: 2025-06-25 02:08:49.365575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e833718e62c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pantry_level', sa.String(), nullable=False))
        batch_op.drop_column('pantry_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pantry_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('pantry_level')

    # ### end Alembic commands ###
