"""empty message

Revision ID: 9286cee9216a
Revises: bd5eee4c5510
Create Date: 2025-06-14 23:20:24.706197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9286cee9216a'
down_revision = 'bd5eee4c5510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False,
               postgresql_using="owner_id::text")

    with op.batch_alter_table('marketplace_item', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using="owner_id::integer")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marketplace_item', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using="owner_id::text")

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               postgresql_using="owner_id::integer")

    # ### end Alembic commands ###
