"""Initial migration with String owner_id

Revision ID: ba1157e2029c
Revises: 
Create Date: 2025-06-19 22:50:12.757527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba1157e2029c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    with op.batch_alter_table('marketplace_item', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.drop_column('pickup_location')
        batch_op.drop_column('instructions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marketplace_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructions', sa.TEXT(), server_default=sa.text("'No instructions provided'::text"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('pickup_location', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.alter_column('owner_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
