"""empty message

Revision ID: bd5eee4c5510
Revises: c0f699e76d0d
Create Date: 2025-06-14 23:19:55.653043

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bd5eee4c5510'
down_revision = 'c0f699e76d0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    with op.batch_alter_table('marketplace_item', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.drop_column('pickup_location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marketplace_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_location', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.alter_column('owner_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    op.create_table('items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('room_no', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pantry_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('expiry_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.CheckConstraint('quantity >= 0', name=op.f('check_quantity')),
    sa.PrimaryKeyConstraint('id', name=op.f('items_pkey'))
    )
    # ### end Alembic commands ###
