"""Add pickup_location to MarketplaceItem

Revision ID: c0f699e76d0d
Revises: d0b5e965c663
Create Date: 2025-06-09 20:05:06.253447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0f699e76d0d'
down_revision = 'd0b5e965c663'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marketplace_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_location', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marketplace_item', schema=None) as batch_op:
        batch_op.drop_column('pickup_location')

    # ### end Alembic commands ###
