"""Add instructions field to Marketplace Item

Revision ID: fdd0a490fb14
Revises: c0f699e76d0d
Create Date: 2025-06-13 14:39:39.783148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdd0a490fb14'
down_revision = 'c0f699e76d0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marketplace_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructions', sa.Text(), nullable=False,  server_default='No instructions provided'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marketplace_item', schema=None) as batch_op:
        batch_op.drop_column('instructions')

    # ### end Alembic commands ###
